import streamlit as st
import torch
import numpy as np
import json
from sklearn.metrics.pairwise import cosine_similarity

# --- PAGE CONFIG ---
st.set_page_config(page_title="NexusNode | LoL Draft AI", page_icon="🎮")

# --- LOAD DATA ---
@st.cache_resource
def load_model_data():
    # Load the embeddings generated by your GNN
    embeddings = torch.load('champion_embeddings.pt', weights_only=False)
    champ_list = sorted(list(embeddings.keys()))
    
    # Load the role mapping from your new preprocess script
    with open('champion_roles.json', 'r') as f:
        role_mapping = json.load(f)
        
    return embeddings, champ_list, role_mapping

embeddings, champ_list, role_mapping = load_model_data()

# --- HEADER ---
st.title("🔗 NexusNode")
st.subheader("GNN-Powered Win-Condition Synthesis")
st.markdown("""
    Select your 4 teammates' champions and **your intended role**. 
    The AI will suggest picks that actually belong in your lane and maximize team synergy.
""")

# --- SIDEBAR / INPUTS ---
st.sidebar.header("The Draft")

# 1. User Role Selection
user_role = st.sidebar.selectbox(
    "What is YOUR Role?", 
    ["TOP", "JUNGLE", "MIDDLE", "BOTTOM", "UTILITY"],
    help="The AI will only suggest champions meta-relevant to this role."
)

st.sidebar.divider()
st.sidebar.write("Enter Teammates:")
# 2. Teammate Selection (Removed labels like 'Top Lane' to be flexible)
p1 = st.sidebar.selectbox("Teammate 1", champ_list, index=0)
p2 = st.sidebar.selectbox("Teammate 2", champ_list, index=1)
p3 = st.sidebar.selectbox("Teammate 3", champ_list, index=2)
p4 = st.sidebar.selectbox("Teammate 4", champ_list, index=3)

selected_teammates = [p1, p2, p3, p4]

# --- RECOMMENDATION LOGIC ---
def get_recommendations(teammates, target_role):
    # Get vectors for the 4 teammates
    team_vectors = [embeddings[name] for name in teammates]
    team_centroid = np.mean(team_vectors, axis=0).reshape(1, -1)
    
    # Get the list of valid champions for the selected role
    valid_role_champs = role_mapping.get(target_role, [])
    
    scores = []
    for champ in valid_role_champs:
        # Check if champ is in our GNN embeddings and NOT already picked
        if champ in embeddings and champ not in teammates:
            vector = embeddings[champ]
            sim = cosine_similarity(team_centroid, vector.reshape(1, -1))[0][0]
            scores.append((champ, sim))
    
    # Sort by similarity score
    return sorted(scores, key=lambda x: x[1], reverse=True)[:5]

# --- MAIN DISPLAY ---
if st.button("Synthesize My Best Pick"):
    results = get_recommendations(selected_teammates, user_role)
    
    if not results:
        st.error(f"No valid suggestions found for {user_role}. Check your data collection!")
    else:
        st.write(f"### 🏆 Top {user_role} Picks for this Comp")
        
        cols = st.columns(len(results))
        for i, (champ, score) in enumerate(results):
            with cols[i]:
                st.metric(label=f"Rank {i+1}", value=champ)
                st.write(f"**{score:.2%}** Synergy")
        
        st.success(f"Analysis Complete: These {user_role} picks maximize vector similarity to high-ELO winning compositions.")

else:
    st.info("Fill out the draft in the sidebar and click 'Synthesize' to find your pick.")

# --- TECHNICAL FOOTER ---
st.divider()
with st.expander("Technical Architecture"):
    st.write(f"""
        - **Constraints:** Filtered results to **{len(role_mapping.get(user_role, []))}** meta-relevant {user_role} champions.
        - **Method:** Centroid-based Cosine Similarity in a 64D Graph Embedding space.
        - **Data Source:** Challenger Tier Match-V5 via Riot API.
    """)